name: CI/CD - Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # Trigger deployment on main branch

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1 Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️ Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 44 Run tests
      - name: Run PyTest
        run: |
          pytest -v tests

      # 5️ Install git-lfs (needed for pushing large files if using LFS)
      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      # 6️ Configure HF token
    - name: Configure Hugging Face token
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote add hf https://$HF_TOKEN@huggingface.co/spaces/jseiden/cifar10-fastapi

    # 7️ Push code to Hugging Face Space
    - name: Deploy to Hugging Face Space
      run: git push hf main --force
